config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :people do
    resources :payments
  end
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :person, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :payments
  validates :name, presence: true, length: {minimum: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @person = Person.find(params[:person_id])
    @payments = @person.payments
  end

  def create
    @person = Person.find(params[:person_id])
    @payment = Payment.new(payment_params)
    if @payment.save
      redirect_to person_path(@person)
    else
      render 'new'
    end
  end

  def new
    @person = Person.find(params[:person_id])
    @payment = Payment.new
  end

  private
    def payment_params
      params.require(:payment).permit(:description, :amount, :timelog)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render 'new'
    end
  end

  def update
    @person = Person.find(params[:id])

    if @person.update
      redirect_to people_path
    else
      render 'edit'
    end
  end

  def new
    @person = Person.new
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private
    def person_params
      params.require(:person).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/home/index.html.erb
<div class = "headerbg">
  <h1 id = "appheader">BreakEven</h1>
</div>
<p>Do you feel like your partner spends too much on you?</p>
<p>Or maybe that you're always the one to pick up the bill?</p>
<p>We have something to help keep each of you accountable for your spending!</p>
<p id="secret">(or at least provide enough proof for you to back up your most recent bill grab on Valentine's Day)</p>
<button><%= link_to 'Continue', controller = 'people' %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paymedateme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<h2><%= @person.name %>'s
  Payments:</h2>
<%= total = 0 %>
  <table>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Date</th>
    </tr>
    <%= @person.payments.each do |payment| %>
      <tr>
        <td><%= payment.description %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.timelog %> </td>
      </tr>
      <%= total += payment.amount %>
    <% end %>
  </table>
  <p>Total:</p>
  <p><%= total %></p>
<% end %>

app/views/payments/new.html.erb
<h2 class="headerbg">Log <%= @person.name %>'s payment</h2>

<%= form_for [@person, @payment] do |form| %>
  <% if @payment.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %>
        are causing issues: </h2>
      <ul>
        <%= @payment.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :description %>:<br>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label :amount %>:<br>
    <%= form.text_field :amount %>
  </p>
  <p>
    <%= form.label :timelog %><br>
    <%= form.text_field :timelog %>
  </p>

  <p> <%= form.submit %></p>
<% end %>

app/views/people/_form.html.erb
<%= form_with scope: :person, url: people_path, local:true do |form|%>
  <% if @person.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %>
        are causing issues: </h2>
      <ul>
        <%= @person.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %>:<br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/people/edit.html.erb
<div class = "headerbg">
  <h2>Edit name:</h2>
</div>

<%= render 'form' %>

<p>
  <%= link_to 'Back', :back %>
</p>

app/views/people/index.html.erb
<div class = "headerbg">
<h2>People:</h2>
</div>

<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><button><%= link_to "Delete this person", person_path(person), method: :delete, data: {confirm: "Are you sure?"} %></button></td>
    <td><button><%= link_to "Edit name", edit_person_path(person) %></button></td>
    <td><button><%= link_to "Add new payment", new_person_payment_path(person)%></button></td>
  </tr>
<% end %>
</table>

<button><%= link_to "Add new person", new_person_path(@person) %></button>
<div>
  <ul>
      <% @people.each do |person| %>
      <li><%= link_to "See all of ".concat(person.name).concat("'s payments"), person_payments_url(person) %></li>
      <% end %>
    </ul>
</div>

<p>
  <%= link_to "Back", :back %>
</p>

app/views/people/new.html.erb
<div class = "headerbg">
<h2>Add a person:</h2>
</div>
<%= render 'form' %>
<%= link_to 'Back', :back %>